name: "action-docker-bun-release"
description: "Builds and pushes a Docker image to a registry using the bundled Dockerfile"
author: "Raphael Goetz <contact@packforge.zip>"
branding:
  icon: "package"
  color: "blue"

inputs:
  registry:
    description: "Container registry (e.g. ghcr.io)"
    required: false
    default: "ghcr.io"
  image_name:
    description: "Image name"
    required: true
  dockerfile:
    description: "Path to bundled Dockerfile inside this action (relative to action root)"
    required: false
    default: "Dockerfile"
  token:
    description: "GitHub token with packages write permissions"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout caller repo
      uses: actions/checkout@v4

    - name: Copy bundled Dockerfile into workspace
      run: |
        cp "${GITHUB_ACTION_PATH}/docker-images/${{ inputs.dockerfile }}" "${GITHUB_WORKSPACE}/Dockerfile"
      shell: bash

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.token }}
        
    - name: Extract metadata (tags & labels)
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ inputs.registry }}/${{ inputs.image_name }}

    - name: Build & push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ${{ github.workspace }}
        file: Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
